name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js (v22)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalación de Dependencias
        run: |
          npm install --os=darwin --cpu=arm64
          npm install --include=optional

      - name: Build del proyecto web
        run: npm run build

      - name: Reconstruir Proyecto iOS
        run: |
          # Eliminamos la carpeta ios por si está corrupta o incompleta
          rm -rf ios
          # Agregamos la plataforma e instalamos los archivos base
          npx cap add ios
          npx cap sync ios

      - name: Instalar CocoaPods
        run: |
          cd ios/App
          # Ahora el Podfile tiene que existir porque lo acabamos de generar
          pod install

      - name: Compilar para iOS (Xcode)
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -configuration Debug \
                     -sdk iphoneos \
                     -destination 'generic/platform=iOS' \
                     build CODE_SIGNING_ALLOWED=NO