name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js (v22)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalación de Dependencias
        run: |
          npm install --os=darwin --cpu=arm64
          npm install --include=optional

      - name: Build del proyecto web
        run: npm run build

      - name: Sincronizar y Parchear AppDelegate (Universal Links Fix)
        run: |
          rm -rf ios
          npx cap add ios
          npx cap update ios
          npx cap sync ios
          
          # PARCHE QUIRÚRGICO:
          # Convertimos el userActivity en su URL interna para que Capacitor lo acepte.
          # Esto cambia la llamada a: .application(application, userActivity.webpageURL)
          sed -i '' 's/continue: userActivity, restorationHandler: restorationHandler/userActivity.webpageURL/g' ios/App/App/AppDelegate.swift
          sed -i '' 's/continue: userActivity/userActivity.webpageURL/g' ios/App/App/AppDelegate.swift

          xcodebuild -resolvePackageDependencies -project ios/App/App.xcodeproj -scheme App

      - name: Compilar para iOS (Xcode)
        run: |
          xcodebuild clean build \
                     -project ios/App/App.xcodeproj \
                     -scheme App \
                     -configuration Debug \
                     -sdk iphoneos \
                     -destination 'generic/platform=iOS' \
                     CODE_SIGNING_ALLOWED=NO \
                     COMPILER_INDEX_STORE_ENABLE=NO \
                     GCC_WARN_INHIBIT_ALL_WARNINGS=YES